import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang="ja">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="notification-icon" href="/icon-192x192.png" />
        <meta name="theme-color" content="#4a90e2" />
      </head>
      <body className={inter.className}>
        <main className="min-h-dvh w-screen">{children}</main>
      </body>
    </html>
  )
}

export default RootLayout
